import "./globals.css";
import { ClusterProvider } from "@/app/components/cluster/cluster-data-access";
import { SolanaProvider } from "@/app/components/solana/solana-provider";

import { ReactQueryProvider } from "./react-query-provider";
import { Header } from "@/app/components/Header";
import { Baskervville } from "next/font/google";

const baskervville = Baskervville({
	weight: ["400"],
	subsets: ["latin"],
});

export const metadata = {
	title: "Testudo",
	description: "Generated by create-solana-dapp",
};

const links: { label: string; path: string }[] = [
	{ label: "Account", path: "/account" },
	{ label: "Clusters", path: "/clusters" },
	{ label: "Basic Program", path: "/basic" },
];

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${baskervville.className} bg-[#0c1221] text-gray-200 min-h-screen`}>
				<ReactQueryProvider>
					<ClusterProvider>
						<SolanaProvider>
							<div className="flex flex-col min-h-screen">
								<Header />
								<main className="flex-grow pt-28">
									{children}
								</main>
							</div>
						</SolanaProvider>
					</ClusterProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
