[toolchain]
anchor_version = "0.31.0"

[features]
resolution = true

skip-lint = false

[programs.localnet]
testudo = "8ZkK4KPmwwskr2YTjejuHL2sHYyvSmkZauUJY7gyrZ5U"

[programs.devnet]
testudo = "8ZkK4KPmwwskr2YTjejuHL2sHYyvSmkZauUJY7gyrZ5U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[test.validator]
bind_address = "127.0.0.1"
ledger = "./test-ledger"
rpc_port = 8899
enable_rpc_transaction_history = true
rpc_cors = "any"