[toolchain]
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
testudo = "BJUZAVsokNjVti3Rq9ExxkWTavkDtutqHsBdarfgpoxN"

[programs.localnet]
testudo = "BJUZAVsokNjVti3Rq9ExxkWTavkDtutqHsBdarfgpoxN"

[programs.mainnet]
testudo = "BJUZAVsokNjVti3Rq9ExxkWTavkDtutqHsBdarfgpoxN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/testudo2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 7000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = "./test-ledger"
rpc_port = 8899
